### ISSUE TITLE
[Feature]: 채팅 기능이 필요합니다.

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/practice#43]
### Story

현재 채팅이 없기 때문에 친구와 채팅을 할 수 없습니다.
채팅 기능이 추가된다면 생기있는 커뮤니티 형성이 가능할 것 입니다.

### Task completion criteria

- [ ] 친구 등록이 가능한가
- [ ] 등록한 친구와 채팅이 가능한가
- [ ] 친구 외에도 채팅이 가능한가

**Comment by cryscham123** [comment]
친구와 채팅이 아직 안되기 때문에 reopen 합니다

**Comment by cryscham123** [comment]
다음과 같은 기능을 추가로 요청합니다.

- [ ] 하마와도 채팅이 가능해야합니다.

**Comment by cryscham123** [comment]
다음과 같은 기능을 추가로 요청합니다.

- [ ] 하마와 채팅이 가능해야 합니다.

**Comment by cryscham123** [comment]
다음과 같은 기능을 추가로 요청합니다.

- [ ] 하마와 채팅이 가능해야 합니다.

**Comment by cryscham123** [comment]
다음과 같은 기능을 추가로 요청합니다.

- [x] 하마와 채팅이 가능해야 합니다.

**Comment by cryscham123** [comment]
test

**Comment by cryscham123** [comment]
asdasd

**Comment by cryscham123** [comment]
뭐 추가해주세요
