### ISSUE TITLE
[Feature]: github action으로 등록 필요한 기능

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/practice#55]
### Story

몰라

### Task completion criteria

- [ ] last commit date update
- [ ] main에 pr시, microservice architecture에 걸맞은 unit test 의사 코드
- [ ] main에 pr시, 자동 build 의사 코드
- [ ] 자동 deploy 의사 코드
