### ISSUE TITLE
[Feature]: 정기적인 회의 관련 rule을 정해야 합니다.

### ISSUE THREAD

**Issue by cryscham123** [organization-for-practice/practice#56]
### Story

몰라 쓰기 귀찮아

### Task completion criteria

- [ ] daily meeting에 대한 구체적인 내용
- [ ] sprint planning에 대한 구체적인 내용
- [ ] sprint retrospective에 대한 구체적인 내용
- [ ] daily meeting에 대한 참여가 저조할 때에 대한 방안 ( 세번 이상 참여 안하면 영구 제명 생각 중 )
